algo = input('Digite  algo: ')

print('O tipo primitivo deste valor é: {}'.format(type(algo)))
print('Só tem espaços? {}'.format(algo.isspace()))
print('É um número? {}'.format(algo.isnumeric()))
print('É alfabetico? {}'.format(algo.isalpha()))
print('É alfanumerico? {}'.format(algo.isalnum()))
print('Está em maiúsculo? {}'.format(algo.isupper()))
print('Está em minúculo? {}'.format(algo.islower()))
print('Está capitalizada? {}'.format(algo.istitle()))
